// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppState {
    "appVersion": string;
    "injector": InjectorSettings;
    "plugins": PluginInfo[] | null;
    "themes": ThemeInfo[] | null;
    "activeThemeId": string;
    "whatsappUrl": string;
    "remoteOrigin": string;
    "profiles": ProfileInfo[] | null;
    "activeProfileId": string;
}

export interface InjectorSettings {
    "enabled": boolean;
}

export interface PluginInfo {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "enabled": boolean;
    "globalEnabled": boolean;
    "profileOverride"?: boolean | null;
    "entry": string;
}

export interface ProfileInfo {
    "id": string;
    "name": string;
    "accent": string;
}

export interface ThemeInfo {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "enabled": boolean;
    "active": boolean;
    "editable": boolean;
    "entry": string;
}
