// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function ClearPluginOverride(profileID: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(2557691403, profileID, id);
}

export function CreateProfile(name: string): $CancellablePromise<model$0.ProfileInfo> {
    return $Call.ByID(1344118072, name);
}

export function CreateTheme(name: string, source: string): $CancellablePromise<string> {
    return $Call.ByID(972062824, name, source);
}

export function DeleteProfile(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(1318288425, profileID);
}

export function DeleteTheme(id: string): $CancellablePromise<void> {
    return $Call.ByID(1906521081, id);
}

export function GetProfileState(profileID: string): $CancellablePromise<model$0.AppState> {
    return $Call.ByID(4089782047, profileID);
}

export function GetState(): $CancellablePromise<model$0.AppState> {
    return $Call.ByID(3821366202);
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(2381343983);
}

export function OpenPluginProject(id: string): $CancellablePromise<string> {
    return $Call.ByID(2933541245, id);
}

export function OpenSurface(surface: string): $CancellablePromise<void> {
    return $Call.ByID(1517632846, surface);
}

export function ReadTheme(id: string): $CancellablePromise<string> {
    return $Call.ByID(1987732348, id);
}

export function ReloadWhatsApp(): $CancellablePromise<void> {
    return $Call.ByID(3302043732);
}

export function RenameProfile(profileID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1103128350, profileID, name);
}

export function RequestClose(): $CancellablePromise<void> {
    return $Call.ByID(3093136164);
}

export function SelectProfile(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(1667403392, profileID);
}

export function SetInjectorEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1707057218, enabled);
}

export function SetPluginEnabled(id: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(268033335, id, enabled);
}

export function SetPluginEnabledForProfile(profileID: string, id: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3346133471, profileID, id, enabled);
}

export function SetThemeEnabled(id: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3317478175, id, enabled);
}

export function ToggleMaximise(): $CancellablePromise<void> {
    return $Call.ByID(2120138748);
}

export function UpdateTheme(id: string, name: string, source: string): $CancellablePromise<void> {
    return $Call.ByID(3280800183, id, name, source);
}
